# Generated by Django 5.1.1 on 2024-09-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_online_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateRoom',
            fields=[
                ('prid', models.AutoField(primary_key=True, serialize=False)),
                ('username_string', models.CharField(max_length=1000)),
                ('private_room_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
